### ISSUE TITLE
User cannot remove himself from group

### ISSUE THREAD

**Issue by SmalkiGroove** [thecampagnards/docktor#175]
Front and maybe back to fix

**Comment by thecampagnards** [comment]
I think it's a front error because the back seems good <https://innersource.soprasteria.com/dep/project-templates/iac-template/merge_requests/3> maybe we should also redirect him to the groups page

**Comment by thecampagnards** [comment]
Error: **"Group admin permission required"** when it check if your have **WithGroupAdmin** for the POST path **"/updateuser/:username/:status"**
