### ISSUE TITLE
Error when remove container inside daemon view

### ISSUE THREAD

**Issue by thecampagnards** [thecampagnards/docktor#272]
The remove button call group save container but we are inside the daemon view so we don't have group id look https://github.com/thecampagnards/docktor/commit/b6845517463bd67383d3aa93f1eab31e6559476e

**Comment by thecampagnards** [comment]
@SmalkiGroove tu pourras me dire si ça te parait bien ou pas pls ?

**Comment by SmalkiGroove** [comment]
👍
